# Use postgres/example user/password credentials
services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: adminpwd
      POSTGRES_USER: admin
      POSTGRES_DB: nyum
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nyum_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kuprov@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adminpwd
    networks:
      - nyum_network

#  localstack:
#    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
#    image: localstack/localstack
#    ports:
#      - "127.0.0.1:4566:4566"            # LocalStack Gateway
#      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
#    environment:
#      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
#      - DEBUG=${DEBUG:-0}
#    volumes:
#      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"

#  seaweedfs:
#    image: chrislusf/seaweedfs:latest
#    restart: always
#    ports:
#      - "9333:9333"  # SeaweedFS master port
#      - "8080:8080"  # SeaweedFS volume server port
#    command:
#      - server -s3 -dir="/data"
#      - volume -dir="/data" -max=5  -mserver="localhost:9333" -port=8080
#    volumes:
#      - seaweedfs_data:/data
#    networks:
#        - nyum_network
volumes:
  pgdata:
#  seaweedfs_data:

networks:
  nyum_network:

