version: 2
run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - gocognit
    - goconst
    - gocritic
    - unused
    - gosec
    - gocyclo
    - goconst
    - misspell
    - lll
    - unparam
    - nakedret
    - prealloc
    - noctx
    - rowserrcheck
    - sqlclosecheck

  disable:
    - errcheck

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false

    govet:
      enable-all: true

    gocyclo:
      min-complexity: 15

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

    lll:
      line-length: 140

    unparam:
      check-exported: false

    nakedret:
      max-func-lines: 30

    prealloc:
      simple: true
      range-loops: true
      for-loops: false

  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - goimports
          - govet
          - staticcheck
          - unused
          - gosimple
          - ineffassign
          - lll
          - unparam
          - nakedret
          - prealloc
    paths:
        - "vendor/*"
        - "testdata/*"
        - "examples/*"
        - "mocks/*"
        - "mockgen/*"
        - "cmd/*"
        - "pkg/gen/*"

output:
  formats:
    text:
      path: "stdout"
      print-linter-name: true
      print-issued-lines: true
      colors: true


severity:
  default: error
  rules:
    - linters:
        - misspell
      severity: warning