# Base image with Go, Postgres client, Goose, and River
FROM golang:1.25.6

# Install PostgreSQL client
RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Install Goose
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# Install River
RUN go install github.com/riverqueue/river/cmd/river@latest

# Set working directory
WORKDIR /app

# Pre-cache common Go modules that don't change often
RUN go mod init temp && \
    go get connectrpc.com/connect@v1.18.1 && \
    go get github.com/go-chi/chi/v5@v5.2.2 && \
    go get github.com/google/uuid@v1.6.0 && \
    go get github.com/jackc/pgx/v5@v5.7.4 && \
    go get github.com/joho/godotenv@v1.5.1 && \
    go get github.com/pressly/goose/v3@v3.24.3 && \
    go get github.com/riverqueue/river@v0.22.0 && \
    go get github.com/stretchr/testify@v1.10.0 && \
    go get golang.org/x/crypto@v0.38.0 && \
    go get google.golang.org/protobuf@v1.36.6 && \
    rm -rf /app

WORKDIR /app
