# Use postgres/example user/password credentials
services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: adminpwd
      POSTGRES_USER: admin
      POSTGRES_DB: nyum
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nyum_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kuprov@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adminpwd
    networks:
      - nyum_network

  localstack-s3:
    image: localstack/localstack:s3-latest
    ports:
      - "4566:4566"  # LocalStack Gateway
    networks:
      - nyum_network
    volumes:
      - localstack:/localstack/data

volumes:
  pgdata:
  localstack:

networks:
  nyum_network:

