apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyumspace-api
  labels:
    app: nyumspace-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nyumspace-api
  template:
    metadata:
      name: nyumspace-api
      labels:
        app: nyumspace-api
    spec:
      containers:
        - name: nyumspace-api
          image: nyumspace-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      