{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: nyumspace
type: Opaque
stringData:
  PGUSER: {{ .Values.postgres.credentials.user | quote }}
  PGPASSWORD: {{ .Values.postgres.credentials.password | quote }}
  PGDATABASE: {{ .Values.postgres.credentials.db | quote }}
  PGHOST: "postgres"
  PGPORT: "5432"
{{- end }}
